"use client";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {Layout} from "antd";
const {Content, Sider} = Layout;
import AppHeader from "@/component/AppHeader";
import AppSideMenu from "@/component/AppSideMenu";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AntdRegistry>
                    <Layout>
                        <AppHeader />

                        <Layout hasSider>
                            <Sider
                                style={{
                                    position: "fixed",
                                    height: "100vh",
                                    overflow: "auto",
                                    left: 0,
                                    backgroundColor: "rgb(110, 178, 236)",
                                    zIndex: 1000,
                                }}
                            >
                                <AppSideMenu />
                            </Sider>

                            <Layout>
                                <Content className="site-maincontent">{children}</Content>
                            </Layout>
                        </Layout>
                    </Layout>
                </AntdRegistry>
            </body>
        </html>
    );
}
